title: Masterclass
remote_theme: just-the-docs/just-the-docs@main

aux_links:
  "<img src='https://cdn.simpleicons.org/github/white' width=24/>":
    - "https://github.com/francescobianco/masterclass"
  "<img src='https://cdn.simpleicons.org/discord/white' width=24/>":
    - "https://discord.com/invite/SVx7JHjAcY"

footer_content: >
  © 2021 DX Tech Papers
  <style>.field-list th, footer.site-footer { display: none; }</style>
